version: '3'
services: 
  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx
    ports: 
      - "8080:8080"
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
    networks: 
      - dev-frontend
  hello1:
    build: ./app/hello1 
    ports: 
      - "8000"
    environment: 
      - NODE_ENV=development
    networks: 
      - dev-frontend
      - dev-backend
  hello2:
    build: ./app/hello2
    ports: 
      - "8000"
    environment: 
      - NODE_ENV=development
    networks: 
      - dev-frontend
      - dev-backend
  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379"
    networks: 
      - dev-backend

networks:
  dev-frontend:
    driver: bridge
  dev-backend:
    driver: bridge
