apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  labels:
    name: hello-api
    owner: Navapon
    version: "1.0"
    module: WebServer
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-api
      owner: Navapon
      version: "1.0"
      module: WebServer
      environment: development
  template:
    metadata:
      labels:
        name: hello-api
        owner: Navapon
        version: "1.0"
        module: WebServer
        environment: development
    spec:
      containers:
        - name: hello-api
          image: hello1:development-10
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
